name: "Fetch and Save"
description: "Fetch something from a URL, and save it in a directory"
inputs:
  url:
    description: "The url"
    required: true
    default: ""
  filename:
    description: "The filename"
    required: false
    default: ""
  target:
    description: "Target file destination"
    required: true
    default: "."
  auto-match:
    description: 'Match the first URL from "url"'
    required: false
    default: "false"
outputs:
  filename:
    description: "Written file name"
runs:
  using: node12
  main: dist/index.js
